version: "3.8"

services:
  backend:
    build:
      context: ./llm-backend
      dockerfile: Dockerfile
    volumes:
      - ./llm-backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/dbname
    depends_on:
      - mongo

  frontend:
    build: ./llm-chat-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
